### ISSUE TITLE
Time estimate way understated

### ISSUE THREAD

**Issue by brianjmurrell** [launchableinc/cli#487] opened 2022-10-30 17:26 UTC
When I try to create a subset I get a time estimate that is entirely unreasonably low and a large number of tests.  It's orthogonal, but I wonder if the large number of tests is because Launchable can request 423 tests thinking they will take less than a second in total.

I.e.:

```
[2022-10-28T17:25:25.462Z] + launchable record build --name jenkins-daos-stack-daos-PR-10701-1 --source src=.
[2022-10-28T17:25:28.742Z] Launchable recorded 1 commit from repository /data/jenkins/jenkins-1/ci_vm_wolf-106vm1-9/workspace/daos-stack_daos_PR-10701
[2022-10-28T17:25:28.742Z] Launchable recorded build jenkins-daos-stack-daos-PR-10701-1 to workspace daos-stack/daos with commits from 2 repositories:
[2022-10-28T17:25:28.742Z] 
[2022-10-28T17:25:28.742Z] | Name             | Path           | HEAD Commit                              |
[2022-10-28T17:25:28.742Z] |------------------|----------------|------------------------------------------|
[2022-10-28T17:25:28.742Z] | src              | .              | 23b728a5dc225a743020390a3d57ed16c962a1df |
[2022-10-28T17:25:28.742Z] | src/src/rdb/raft | ./src/rdb/raft | c18bcb8ef18d5937558e881cd48a7568982aa954 |
[2022-10-28T17:25:28.742Z] + launchable subset --target 80% --build jenkins-daos-stack-daos-PR-10701-1 pytest
[2022-10-28T17:25:43.649Z] dfuse/daos_build.py::test_dfuse_daos_build_data
[2022-10-28T17:25:43.649Z] pool/destroy.py::test_destroy_wrong_group
[2022-10-28T17:25:43.649Z] dfuse/daos_build.py::test_dfuse_daos_build_wt
...
[2022-10-28T17:25:43.656Z] object/integrity.py::test_invalid_tx_commit_close
[2022-10-28T17:25:43.656Z] harness/advanced.py::test_launch_failures
[2022-10-28T17:25:43.656Z] cart/ghost_rank_rpc/ghost_rank_rpc_one_node.py::test_cart_ghost_rank_rpc
[2022-10-28T17:25:43.656Z] Launchable created subset 361113 for build jenkins-daos-stack-daos-PR-10701-1 (test session 1526834) in workspace daos-stack/daos
[2022-10-28T17:25:43.656Z] 
[2022-10-28T17:25:43.656Z] |           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
[2022-10-28T17:25:43.656Z] |-----------|--------------|--------------------------|----------------------------|
[2022-10-28T17:25:43.656Z] | Subset    |          423 |                  79.9622 |                 0.00705    |
[2022-10-28T17:25:43.656Z] | Remainder |          106 |                  20.0378 |                 0.00176667 |
[2022-10-28T17:25:43.656Z] |           |              |                          |                            |
[2022-10-28T17:25:43.656Z] | Total     |          529 |                 100      |                 0.00881667 |
[2022-10-28T17:25:43.656Z] 
[2022-10-28T17:25:43.656Z] Run `launchable inspect subset --subset-id 361113` to view full subset details
```

I believe the timing data we are submitting for tests is being specified properly in the junit submissions.  Here's an example:

```xml
<testsuite errors="0" failures="0" name="job-2022-10-27T21.20-fa88ba3" skipped="0" tests="1" time="53.097" timestamp="2022-10-27T21:21:00.283826">
<testcase classname="SimpleCreateDeleteTest" name="test_container_basics" file="./container/simple_create_delete.py" time="53.097"/>
...
</testsuite>
```

Any ideas why Launchable thinks our tests run so quickly?

**Comment by awilkes** [comment] 2022-11-01 16:09
Hi Brian, thanks for taking the time to report this issue.

The underlying problem is that the subset service did not recognize any of the input test paths. Looking at your data, I suspect this is caused by a bug in the CLI's pytest integration. I will check with the team and get back to you as soon as possible.

----

Compounding the issue, the UX for discovering this problem is bad. When a test is unrecognized, the service assigns it an estimated duration of 0.001s. That explains the low estimated duration (423 tests x 0.001s/test x 1m/60s = 0.00705m). But this is clearly not the best way to expose this issue! We need to:

1. Expose the recognized/unrecognized counts in the subset summary output
2. Stop assigning a low duration to unrecognized tests (this is not needed anymore) and/or only sum the estimated duration for recognized tests
3. Provide a list of unrecognized tests and/or warn when too many tests are unrecognized to aid in troubleshooting

If we did that, you would have been able to write an issue like "Launchable didn't recognize my tests, what's the issue?" There would still be a problem (unrecognized tests), but it would be more obvious.

**Comment by brianjmurrell** [comment] 2022-11-01 17:27
> Hi Brian, thanks for taking the time to report this issue.

Thanks for your response.
 
> The underlying problem is that the subset service did not recognize any of the input test paths.

This would relate to a [previous issue](https://github.com/launchableinc/cli/issues/450) here where [I asked how I could query the lists of tests recorded for a session](https://github.com/launchableinc/cli/issues/450#issuecomment-1252872564) and was told about `launchable inspect tests`.  In doing so I got results that looked like:

```
| Test Path                                                                                                              |   Duration (sec) | Status   | Uploaded At                 |
|------------------------------------------------------------------------------------------------------------------------|------------------|----------|-----------------------------|
| file=security/cont_get_acl.py#class=GetContainerACLTest#testcase=test_get_acl_valid                                    |           68.741 | SUCCESS  | 2022-10-31T20:15:16.507452Z |
| file=pool/evict.py#class=EvictTests#testcase=test_evict                                                                |           85.98  | SUCCESS  | 2022-10-31T20:15:16.507452Z |
| file=pool/destroy.py#class=DestroyTests#testcase=test_recursivedestroy_with_containers                                 |           52.636 | SUCCESS  | 2022-10-31T20:15:16.507452Z |
...
```

> Compounding the issue, the UX for discovering this problem is bad. When a test is unrecognized, the service assigns it an estimated duration of 0.001s. That explains the low estimated duration (423 tests x 0.001s/test x 1m/60s = 0.00705m). But this is clearly not the best way to expose this issue! We need to:
> 
> 1. Expose the recognized/unrecognized counts in the subset summary output
> 2. Stop assigning a low duration to unrecognized tests (this is not needed anymore) and/or only sum the estimated duration for recognized tests
> 3. Provide a list of unrecognized tests and/or warn when too many tests are unrecognized to aid in troubleshooting
> 
> If we did that, you would have been able to write an issue like "Launchable didn't recognize my tests, what's the issue?" There would still be a problem (unrecognized tests), but it would be more obvious.

Indeed!

So given the `launchable inspect tests` output above and given that my input to `launchable subset --target 80% --build jenkins-daos-stack-daos-PR-10701-1 pytest`

Looks like:

```
aggregation/basic.py::test_basic_aggregation
aggregation/checksum.py::test_aggregationchecksum
aggregation/dfuse_space_check.py::test_dfusespacecheck
...
```

and the output from the _subset_ command above is:

```
dfuse/daos_build.py::test_dfuse_daos_build_data
pool/destroy.py::test_destroy_wrong_group
dfuse/daos_build.py::test_dfuse_daos_build_wt
soak/harassers.py::test_soak_harassers
...
```

Where is the test name mismatch?  What should my input look like given the `launchable inspect tests` output above?

**Comment by awilkes** [comment] 2022-11-02 20:06
I haven't been able to get to the bottom of this yet, but I wanted to reply regardless.

From my research, it looks like the issue is in the somewhere in the area of how we manage class names.

We store pytest tests using a structure of `file -> class -> test`. Therefore when we make a subset request we need to submit a list of `file -> class -> test` structures to match up the tests. To achieve this, I believe the CLI takes the output from `pytest --collect-only  -q` and converts it to this structure prior to submission.

However, in this case, the format of the `class` component does not match between the subset request input and the stored path. It's unclear which side the issue lies on (subset request formatting or test recording).

For example, here's two _formatted_ inputs:

```
file=aggregation/checksum.py#class=aggregation.checksum#testcase=test_aggregationchecksum
file=aggregation/dfuse_space_check.py#class=aggregation.dfuse_space_check#testcase=test_dfusespacecheck
```

But here's what we've stored:

```
file=aggregation/checksum.py#class=AggregationChecksum#testcase=test_aggregationchecksum
file=aggregation/dfuse_space_check.py#class=DfuseSpaceCheck#testcase=test_dfusespacecheck
```

The class formatting doesn't line up: `class=aggregation.checksum` versus `class=AggregationChecksum`. Quick question: are you sending reports using `junit_family=legacy`?

We are meeting in person as a team next week, so I can discuss this with engineering then. Apologies in advance for the delay.

In the meantime, there are a few things to consider:

1. If you're able to precisely list tests, you can also try making a request using the [`raw` profile](https://docs.launchableinc.com/resources/integrations/raw#subsetting-your-test-runs) which lets you use the `file#class#testcase` directly with no preprocessing.
2. We've also been [developing an option](https://docs.launchableinc.com/features/predictive-test-selection/requesting-and-running-a-subset-of-tests/zero-input-subsetting) where the input list isn't necessary at all, and we just get the full list of tests directly from the server. That would sidestep this issue too. We haven't tested this process with pytest yet, though, so let me know if that's of interest to you.
3. You could also try the new [Launchable pytest plugin](https://docs.launchableinc.com/resources/integrations/pytest#native-pytest-plugin).

Thank you! I will be in touch next week.

**Comment by awilkes** [comment] 2022-11-02 20:08
FYI @yoshiori

**Comment by brianjmurrell** [comment] 2022-11-03 13:07
> I haven't been able to get to the bottom of this yet, but I wanted to reply regardless.

Thanks, appreciate it.

> We store pytest tests using a structure of `file -> class -> test`. Therefore when we make a subset request we need to submit a list of `file -> class -> test` structures to match up the tests. To achieve this, I believe the CLI takes the output from `pytest --collect-only -q`

Which from my research is of the format `file.py::test_name` according to  https://stackoverflow.com/questions/50728351/using-pytest-collect-only-to-only-return-individual-test-names

> For example, here's two _formatted_ inputs:
> 
> ```
> file=aggregation/checksum.py#class=aggregation.checksum#testcase=test_aggregationchecksum
> file=aggregation/dfuse_space_check.py#class=aggregation.dfuse_space_check#testcase=test_dfusespacecheck
> ```

Where are you getting these from?  Thos class names are wrong.

 
> But here's what we've stored:
> 
> ```
> file=aggregation/checksum.py#class=AggregationChecksum#testcase=test_aggregationchecksum
> file=aggregation/dfuse_space_check.py#class=DfuseSpaceCheck#testcase=test_dfusespacecheck
> ```

Those class names are correct.
 
> The class formatting doesn't line up: `class=aggregation.checksum` versus `class=AggregationChecksum`.

Indeed, hence my question about whee that first one is coming from.

> Quick question: are you sending reports using `junit_family=legacy`?

No:

```
$ launchable record tests --build jenkins-daos-stack-daos-master-7643 pytest *.xml
```

> 1. If you're able to precisely list tests, you can also try making a request using the [`raw` profile](https://docs.launchableinc.com/resources/integrations/raw#subsetting-your-test-runs) which lets you use the `file#class#testcase` directly with no preprocessing.

But just like pytest, my test framework only provides file->test_name.  No class info.

> 2. We've also been [developing an option](https://docs.launchableinc.com/features/predictive-test-selection/requesting-and-running-a-subset-of-tests/zero-input-subsetting) where the input list isn't necessary at all,

It has always puzzled me why an input list is necessary.

> and we just get the full list of tests directly from the server. That would sidestep this issue too. We haven't tested this process with pytest yet, though, so let me know if that's of interest to you.

Sure!  As I said, I don't even know why I should need to supply a list.

> 3. You could also try the new [Launchable pytest plugin](https://docs.launchableinc.com/resources/integrations/pytest#native-pytest-plugin).

My test framework is not actually pytest.  It's a derivative of pytest that works much like pytest.  But it's not pytest.
 
> Thank you!

Thanks!

**Comment by Konboi** [comment] 2022-11-04 06:44
Hi, I investigated this issue. It doesn’t still solve but I share the current status.

> Which from my research is of the format file.py::test_name according to https://stackoverflow.com/questions/50728351/using-pytest-collect-only-to-only-return-individual-test-names

Yes, pytest will outputs not only `file->class->test_case` format but also `file->calss` or `file->test_case`

we support these cases ref: https://github.com/launchableinc/cli/blob/dd254773fa086383669281ee46776e4b151dd7da/launchable/test_runners/pytest.py#L71-L87

However, class name, and test case name must be the same between the subset and the record tests. Also format that reported record test pahse should have equal or more deeply altitude than subset.
e.g)
OK case
subset: `file::class` or `file`
record tests: `file::class::testcsae` or `file::class`

NG case
Subset: `file::class::testcase`
record tests: `file` (lower altitude than the subset)
or 
Subset: `file::class::testcase`
record tests: `file::CLASS::testcase` ( class != CLASS )


> Where are you getting these from? Thos class names are wrong.

These were sent from your side. You can check the subset candidate by `launchable inspect —subset-id 361113`

From your comment, it seems that `pytest —collect-only -q` outputs different test paths format from the reported test paths.

> Those class names are correct.

These paths were stored by `launchable record tests` command from your side.

> Indeed, hence my question about whee that first one is coming from.

same as `Where are you getting these from? Thos class names are wrong.` section

> My test framework is not actually pytest. It's a derivative of pytest that works much like pytest. But it's not pytest.

I guess this is a cause of this issue but I’m not too sure...

**Comment by awilkes** [comment] 2022-11-04 13:35
> Where are you getting these from? Thos class names are wrong.

To expand on this, the CLI automatically generates them from the inputs (based on the file paths). Clearly that's not appropriate in this case, though!

**Comment by brianjmurrell** [comment] 2022-11-08 19:12
> To expand on this, the CLI automatically generates them from the inputs (based on the file paths). Clearly that's not appropriate in this case, though!

Is this saying that this is a bug/mis-behaviour in the `launchable` command in that it's mangling the test names so that they no longer match our submitted test data?

If so, how can this be mitigated?

**Comment by brianjmurrell** [comment] 2022-11-12 15:01
I'm hoping I can get an update here.

**Comment by awilkes** [comment] 2022-11-14 16:16
Yes, there are a few things going on with the input parsing that need to be resolved.

The best path forward is to switch to [Zero Input Subsetting](https://docs.launchableinc.com/features/predictive-test-selection/requesting-and-running-a-subset-of-tests/zero-input-subsetting) so you don't have to generate an input list at all.

We need to make a small update to support this for pytest (and for the raw profile). I'll let you know when that's done.

**Comment by brianjmurrell** [comment] 2022-11-14 16:25
> We need to make a small update to support this for pytest (and for the raw profile). I'll let you know when that's done.

Thanks.  I will stand-by.  :-)

**Comment by awilkes** [comment] 2022-11-14 17:14
Thanks for your patience!

**Comment by awilkes** [comment] 2022-11-16 17:47
When we switch to an inputless subset, we switch from an inclusion mode to an exclusion mode so that new tests run.

Unfortunately, pytest only supports excluding _files_, not testcases. Its inclusion behavior doesn't match its exclusion behavior, so if we add support for inputless subsetting, the granularity will suffer a bit.

Regardless, we **are** adding support for inputless subsetting to the raw profile (it'll output a list of raw testpaths to exclude).

With this in mind, can you check the exclusion capability of your pytest-like runner? What granularity/hierarchy level can it accept? Thanks.

**Comment by brianjmurrell** [comment] 2022-11-16 18:02
I don't know/think that Avocado can accept an exclusion list.  I suppose we can work around it by asking it for a list of all tests and then applying a `grep -v` like function to it to exclude tests.  Does that seem like I'm understanding what you are asking about?

**Comment by awilkes** [comment] 2022-11-16 18:47
Yes 👍

**Comment by brianjmurrell** [comment] 2022-11-17 14:52
Just so I am clear, I am still standing by for the required updates, correct?

**Comment by awilkes** [comment] 2022-11-17 14:56
That's correct.

**Comment by awilkes** [comment] 2022-11-22 18:33
CLI v1.54.0 includes an update that should help here. You can now use `--get-tests-from-previous-sessions` with the `raw` profile. This command outputs raw lists of testpaths that you can manipulate for use with your test runner! Note that since we're relying on previously recorded sessions, in order to make sure _new_ tests to run, it's better to exclude the remainder instead of including the subset (as mentioned above).

Usage:
```
launchable subset --session builds/3526037564/test_sessions/1588481 --target 80% --get-tests-from-previous-sessions --rest=rest.txt raw > subset.txt
```

`rest.txt` will contain the tests you should exclude. Since this list was built from recorded testpaths, everything _should_ line up. Hope that helps.

**Closed** 2023-05-17 18:21 UTC
